import { randomUUID } from "crypto"
import type {
  ReleasePackageInput,
  ReleasePackage,
  ReleasePackageArtifact,
  RiskLevel,
  ReadinessStatus,
  ReleasePackageSources,
  AuditSourceData,
  AsoSourceData,
} from "../../schemas/release-package"

// ── Risk helpers ──────────────────────────────────────────────────────────────

const RISK_RANK: Record<RiskLevel, number> = { low: 0, medium: 1, high: 2 }

function auditRiskLevel(score: number): RiskLevel {
  if (score >= 60) return "high"
  if (score >= 30) return "medium"
  return "low"
}

function asoRiskLevel(aso: AsoSourceData): RiskLevel {
  return aso.warnings.length > 0 ? "medium" : "low"
}

function worstRisk(levels: RiskLevel[]): RiskLevel {
  return levels.reduce<RiskLevel>(
    (worst, current) => (RISK_RANK[current] > RISK_RANK[worst] ? current : worst),
    "low"
  )
}

function deriveReadinessStatus(
  riskLevel: RiskLevel,
  anyMissing: boolean,
  hasBlockingIssues: boolean
): ReadinessStatus {
  if (hasBlockingIssues || riskLevel === "high") return "blocked"
  if (anyMissing || riskLevel === "medium") return "needs-work"
  return "ready"
}

// ── Markdown builders ─────────────────────────────────────────────────────────

type PartialPackage = Omit<ReleasePackage, "releasePacketMarkdown" | "agentExecutionBrief">

function buildReleasePacketMarkdown(
  appId: string,
  input: ReleasePackageInput,
  pkg: PartialPackage
): string {
  const lines: string[] = []

  const versionParts = [
    input.version ? `v${input.version}` : "",
    input.buildNumber ? `build ${input.buildNumber}` : "",
  ].filter(Boolean)

  lines.push(`# Release Package: ${pkg.releaseName}`)
  lines.push("")
  lines.push(
    `_Generated ${pkg.createdAt} · App: \`${appId}\`${versionParts.length > 0 ? ` · ${versionParts.join(" · ")}` : ""}_`
  )
  lines.push("")
  lines.push("---")
  lines.push("")

  const statusEmoji =
    pkg.readinessStatus === "ready" ? "✅" : pkg.readinessStatus === "needs-work" ? "⚠️" : "🚫"
  const riskEmoji =
    pkg.riskLevel === "low" ? "🟢" : pkg.riskLevel === "medium" ? "🟡" : "🔴"

  lines.push(
    `## ${statusEmoji} Readiness: ${pkg.readinessStatus.toUpperCase()} | ${riskEmoji} Risk: ${pkg.riskLevel.toUpperCase()}`
  )
  lines.push("")
  lines.push(`> ${pkg.summary}`)
  lines.push("")

  if (input.submissionGoal) {
    lines.push("## Submission Goal")
    lines.push("")
    lines.push(input.submissionGoal)
    lines.push("")
  }

  if (pkg.blockingIssues.length > 0) {
    lines.push("## 🚫 Blocking Issues")
    lines.push("")
    for (const issue of pkg.blockingIssues) {
      lines.push(`- ❌ ${issue}`)
    }
    lines.push("")
  }

  if (pkg.recommendedNextActions.length > 0) {
    lines.push("## Recommended Next Actions")
    lines.push("")
    for (const action of pkg.recommendedNextActions) {
      lines.push(`- [ ] ${action}`)
    }
    lines.push("")
  }

  if (pkg.appReviewSubmissionNotes) {
    lines.push("## App Review Submission Notes")
    lines.push("")
    lines.push(pkg.appReviewSubmissionNotes)
    lines.push("")
  }

  if (input.reviewerNotesOverride) {
    lines.push("## Reviewer Notes (Override)")
    lines.push("")
    lines.push(input.reviewerNotesOverride)
    lines.push("")
  }

  if (pkg.testFlightChecklist.length > 0) {
    lines.push("## TestFlight Checklist")
    lines.push("")
    for (const item of pkg.testFlightChecklist) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push("")
  }

  if (pkg.appReviewChecklist.length > 0) {
    lines.push("## App Review Checklist")
    lines.push("")
    for (const item of pkg.appReviewChecklist) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push("")
  }

  if (pkg.storeKitChecklist.length > 0) {
    lines.push("## StoreKit Checklist")
    lines.push("")
    for (const item of pkg.storeKitChecklist) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push("")
  }

  if (pkg.metadataChecklist.length > 0) {
    lines.push("## Metadata Checklist")
    lines.push("")
    for (const item of pkg.metadataChecklist) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push("")
  }

  if (input.internalNotes) {
    lines.push("## Internal Notes")
    lines.push("")
    lines.push(input.internalNotes)
    lines.push("")
  }

  lines.push("## Artifacts")
  lines.push("")
  lines.push("| Type | ID | Status | Summary |")
  lines.push("|---|---|---|---|")
  for (const artifact of pkg.includedArtifacts) {
    const status = artifact.included ? "✅ Included" : "❌ Missing"
    lines.push(
      `| ${artifact.type} | \`${artifact.id || "—"}\` | ${status} | ${artifact.summary} |`
    )
  }
  lines.push("")

  lines.push("---")
  lines.push("")
  lines.push(
    "_This release packet was generated by AppOps Agent. Do not submit anything to App Store Connect directly from this document._"
  )

  return lines.join("\n")
}

function buildAgentExecutionBrief(
  appId: string,
  input: ReleasePackageInput,
  pkg: PartialPackage
): string {
  const lines: string[] = []

  lines.push("## Agent Execution Brief: App Store Release Prep")
  lines.push("")

  const versionParts = [
    input.version ? `version ${input.version}` : "",
    input.buildNumber ? `build ${input.buildNumber}` : "",
  ].filter(Boolean)

  lines.push(
    `You are preparing app \`${appId}\`${versionParts.length > 0 ? ` (${versionParts.join(", ")})` : ""} for App Store Review submission.`
  )
  lines.push("")

  if (input.submissionGoal) {
    lines.push(`**Submission goal:** ${input.submissionGoal}`)
    lines.push("")
  }

  lines.push(`**Readiness:** ${pkg.readinessStatus} | **Risk:** ${pkg.riskLevel}`)
  lines.push("")

  if (pkg.blockingIssues.length > 0) {
    lines.push("### ⛔ Blocking Issues (resolve before submission)")
    lines.push("")
    for (const issue of pkg.blockingIssues) {
      lines.push(`- ${issue}`)
    }
    lines.push("")
  }

  if (pkg.recommendedNextActions.length > 0) {
    lines.push("### Recommended Next Actions")
    lines.push("")
    for (const action of pkg.recommendedNextActions) {
      lines.push(`- [ ] ${action}`)
    }
    lines.push("")
  }

  if (pkg.testFlightChecklist.length > 0) {
    lines.push("### TestFlight Checklist")
    lines.push("")
    for (const item of pkg.testFlightChecklist) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push("")
  }

  if (pkg.appReviewChecklist.length > 0) {
    lines.push("### App Review Checklist")
    lines.push("")
    for (const item of pkg.appReviewChecklist) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push("")
  }

  if (pkg.storeKitChecklist.length > 0) {
    lines.push("### StoreKit Checklist")
    lines.push("")
    for (const item of pkg.storeKitChecklist) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push("")
  }

  if (pkg.metadataChecklist.length > 0) {
    lines.push("### Metadata Checklist")
    lines.push("")
    for (const item of pkg.metadataChecklist) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push("")
  }

  if (pkg.appReviewSubmissionNotes) {
    lines.push("### App Review Submission Notes")
    lines.push("")
    lines.push(pkg.appReviewSubmissionNotes)
    lines.push("")
  }

  lines.push("### Instructions")
  lines.push("")
  lines.push("1. Resolve all blocking issues before submitting to App Store Review.")
  lines.push("2. Verify every item in each checklist above.")
  lines.push(
    "3. Copy the App Review Submission Notes into the App Review notes field in App Store Connect."
  )
  lines.push("4. Do not submit anything to App Store Connect automatically.")
  lines.push("5. Confirm each checklist item is complete before marking the release ready.")

  return lines.join("\n")
}

// ── Main generator ────────────────────────────────────────────────────────────

export function generateReleasePackage(
  appId: string,
  appName: string,
  input: ReleasePackageInput,
  sources: ReleasePackageSources
): ReleasePackage {
  const now = new Date().toISOString()
  const id = randomUUID()
  const releaseName =
    input.releaseName ||
    (input.version ? `v${input.version}` : `Release ${now.slice(0, 10)}`)

  const includedArtifacts: ReleasePackageArtifact[] = []
  const riskLevels: RiskLevel[] = []
  const nextActions: string[] = []
  const blockingIssues: string[] = []
  const testFlightChecklist: string[] = []
  const appReviewChecklist: string[] = []
  const storeKitChecklist: string[] = []
  const metadataChecklist: string[] = []
  let anyMissing = false
  let appReviewSubmissionNotes = ""

  // ── Release audit ──────────────────────────────────────────────────────────
  if (input.includeLatestAudit) {
    if (sources.audit) {
      const risk = auditRiskLevel(sources.audit.releaseRiskScore)
      riskLevels.push(risk)
      includedArtifacts.push({
        type: "release-audit",
        id: sources.audit.id,
        included: true,
        summary: sources.audit.summary,
      })
      for (const issue of sources.audit.blockingIssues) {
        if (issue.severity === "high") {
          blockingIssues.push(`[${issue.area}] ${issue.issue} — ${issue.recommendedFix}`)
        }
      }
      testFlightChecklist.push(...sources.audit.checklists.testFlight)
      appReviewChecklist.push(...sources.audit.checklists.appReview)
      if (sources.audit.checklists.storeKit) {
        storeKitChecklist.push(...sources.audit.checklists.storeKit)
      }
    } else {
      anyMissing = true
      includedArtifacts.push({
        type: "release-audit",
        id: "",
        included: false,
        summary: "No release audit found for this app.",
      })
      nextActions.push("Run a release audit to get a risk score and checklist.")
    }
  }

  // ── StoreKit diagnostics ───────────────────────────────────────────────────
  if (input.includeLatestStoreKitSpec) {
    if (sources.storeKitSpec) {
      riskLevels.push(sources.storeKitSpec.riskLevel)
      includedArtifacts.push({
        type: "storekit",
        id: sources.storeKitSpec.id,
        included: true,
        summary: sources.storeKitSpec.summary,
      })
      const requiredItems = sources.storeKitSpec.implementationChecklist
        .filter((item) => item.priority === "required")
        .map((item) => item.task)
      storeKitChecklist.push(...requiredItems)
      if (sources.storeKitSpec.appReviewNotes && !appReviewSubmissionNotes) {
        appReviewSubmissionNotes = sources.storeKitSpec.appReviewNotes
      }
    } else {
      anyMissing = true
      includedArtifacts.push({
        type: "storekit",
        id: "",
        included: false,
        summary: "No StoreKit diagnostics spec found for this app.",
      })
      nextActions.push(
        "Run StoreKit diagnostics to generate an IAP checklist and reviewer notes."
      )
    }
  }

  // ── App Review response ────────────────────────────────────────────────────
  if (input.includeLatestAppReviewResponse) {
    if (sources.appReviewResponse) {
      riskLevels.push(sources.appReviewResponse.riskLevel)
      includedArtifacts.push({
        type: "app-review",
        id: sources.appReviewResponse.id,
        included: true,
        summary: sources.appReviewResponse.summary,
      })
      // App Review response text takes precedence over StoreKit notes
      appReviewSubmissionNotes = sources.appReviewResponse.appReviewResponse
      appReviewChecklist.push(
        "Submit the App Review response text in the Reply to Apple field in App Store Connect."
      )
      if (sources.appReviewResponse.reviewerTestingInstructions) {
        appReviewChecklist.push(
          "Verify reviewer testing instructions are included and up to date."
        )
      }
    } else {
      anyMissing = true
      includedArtifacts.push({
        type: "app-review",
        id: "",
        included: false,
        summary: "No App Review response found for this app.",
      })
      nextActions.push(
        "Generate an App Review response to prepare submission notes and reviewer instructions."
      )
    }
  }

  // ── ASO metadata ───────────────────────────────────────────────────────────
  if (input.includeLatestAsoOutput) {
    if (sources.asoOutput) {
      const risk = asoRiskLevel(sources.asoOutput)
      riskLevels.push(risk)
      includedArtifacts.push({
        type: "aso",
        id: sources.asoOutput.id,
        included: true,
        summary: sources.asoOutput.summary,
      })
      metadataChecklist.push("Verify subtitle is updated in App Store Connect (max 30 chars).")
      metadataChecklist.push("Verify promotional text is updated (max 170 chars).")
      metadataChecklist.push("Verify keyword field is updated (max 100 chars, comma-separated).")
      metadataChecklist.push("Verify description is updated (max 4000 chars).")
      metadataChecklist.push("Verify release notes are updated (max 4000 chars).")
      for (const warning of sources.asoOutput.warnings) {
        metadataChecklist.push(`Review ASO warning: ${warning}`)
      }
    } else {
      anyMissing = true
      includedArtifacts.push({
        type: "aso",
        id: "",
        included: false,
        summary: "No ASO metadata output found for this app.",
      })
      nextActions.push("Generate ASO metadata to optimize your App Store listing.")
    }
  }

  // ── GitHub task bundle ─────────────────────────────────────────────────────
  if (input.includeLatestTaskBundle) {
    if (sources.taskBundle) {
      includedArtifacts.push({
        type: "task-bundle",
        id: sources.taskBundle.id,
        included: true,
        summary: sources.taskBundle.summary,
      })
      if (sources.taskBundle.taskCount > 0) {
        nextActions.push(
          `Review and address ${sources.taskBundle.taskCount} open task(s) from the GitHub task bundle.`
        )
      }
    } else {
      anyMissing = true
      includedArtifacts.push({
        type: "task-bundle",
        id: "",
        included: false,
        summary: "No GitHub task bundle found for this app.",
      })
      nextActions.push(
        "Generate a GitHub task bundle to collect all open tasks for this release."
      )
    }
  }

  // ── Reviewer notes override ────────────────────────────────────────────────
  if (input.reviewerNotesOverride) {
    appReviewSubmissionNotes = input.reviewerNotesOverride
  }

  // Fallback if no submission notes were produced
  if (!appReviewSubmissionNotes) {
    appReviewSubmissionNotes =
      `No App Review response or StoreKit notes available for ${appName}. ` +
      "Generate an App Review response or StoreKit diagnostics spec first."
  }

  // ── Aggregate risk and readiness ───────────────────────────────────────────
  const riskLevel: RiskLevel = riskLevels.length > 0 ? worstRisk(riskLevels) : "low"

  if (riskLevel === "high" && blockingIssues.length === 0) {
    blockingIssues.push(
      "High-risk issues detected in one or more artifacts. Review all included artifacts before submitting."
    )
  }

  const readinessStatus = deriveReadinessStatus(
    riskLevel,
    anyMissing,
    blockingIssues.length > 0
  )

  if (readinessStatus === "blocked") {
    nextActions.unshift("Resolve all blocking issues before submitting to App Store Review.")
  } else if (readinessStatus === "ready") {
    nextActions.push("All checks passed. Ready to submit to App Store Review.")
  }

  // ── Summary ────────────────────────────────────────────────────────────────
  const includedCount = includedArtifacts.filter((a) => a.included).length
  const totalCount = includedArtifacts.length
  const readinessLabel =
    readinessStatus === "ready"
      ? "Release is ready for submission."
      : readinessStatus === "needs-work"
        ? "Release needs work before submission."
        : "Release is blocked and must not be submitted."
  let summary = `${readinessLabel} ${includedCount}/${totalCount} artifact(s) included. Risk: ${riskLevel}.`
  if (blockingIssues.length > 0) {
    summary += ` ${blockingIssues.length} blocking issue(s).`
  }

  // ── Build partial package, then add markdown fields ────────────────────────
  const partial: PartialPackage = {
    id,
    appId,
    releaseName,
    version: input.version,
    buildNumber: input.buildNumber,
    summary,
    readinessStatus,
    riskLevel,
    includedArtifacts,
    appReviewSubmissionNotes,
    testFlightChecklist,
    appReviewChecklist,
    storeKitChecklist,
    metadataChecklist,
    blockingIssues,
    recommendedNextActions: nextActions,
    createdAt: now,
  }

  return {
    ...partial,
    releasePacketMarkdown: buildReleasePacketMarkdown(appId, input, partial),
    agentExecutionBrief: buildAgentExecutionBrief(appId, input, partial),
  }
}
